services:
  postgres:
    container_name: BookWise
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: doker
      POSTGRES_DB: BookWise
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres